### ISSUE TITLE
Expandable Banner

### ISSUE THREAD

**Issue by ManuWilliams-atx** [bastole/fast-banner-template-for-animate-cc#1]
Hi, this is fantastic!
1_ Is this compatible with the latest release of Animate CC?
2_ Are there any plans of providing a template for an expandable unit targeting Doubleclick Studio Rich Media units?

Thanks!

**Comment by bastole** [comment]
Hi, unfortunately this only works with animate CC 2015.
I'm almost done with the expanding unit as well!

**Comment by ManuWilliams-atx** [comment]
Oh thanks for the response! Any ETA as to when it will be posted? Will that
new version work with the latest Animate CC? Thanks!

**Comment by bastole** [comment]
It seems the whole html template and javascript has changed for 2017 and it may take some time to update these for Animate CC 2017. 
In the meantime you can always download 2015.2 from Creative Cloud.
I've got a messy working Expandable template for 2015 and I'll upload it first - maybe in 2~3 days.
Cheers
H

**Comment by bastole** [comment]
@dada78 
I've just updated the files to 2017 version and added expandable banner support :)

**Comment by ManuWilliams-atx** [comment]
Thanks for notifying me and making it publicly available!

**Comment by ManuWilliams-atx** [comment]
Thanks so much for notifying me Han! Will download to test them out! Thanks
again!

**Comment by ManuWilliams-atx** [comment]
Hi Han, I checked out the expandable banner for Doubleclick,but when I uploaded to test on the Doubleclick interface the html gave me the following error:
"Sorry, JOB0000_expand_1000x50to500.html contains an Expanding component and creatives of this format don't support Expanding components." Have you encountered the same issue? Thanks

**Comment by bastole** [comment]
@dada78 , sounds like the creative format is set incorrectly.
When you created a new ad from DC studio, did you select 'Expanding' from the format list?
[Here's the link](http://imgur.com/Et7dhFd)

Cheers

**Comment by ManuWilliams-atx** [comment]
Hi,
After I downloaded from Git today again the expandable only
included:JOB0000_expand_1000x50to500.fla, I tested and then published the
file which resulted in the following files:

bg_collapsed.jpg
bg_expanded.jpg
createjs-2015.11.26.min.js
JOB0000_expand_1000x50to500.html
JOB0000_expand_1000x50to500.js

However nothing was showing in the test preview and the console output was:
Uncaught TypeError: Cannot read property 'style' of undefined
    at show (JOB0000_expand_1000x50to500.html:111)
    at checkLoaded (JOB0000_expand_1000x50to500.html:80)
    at HTMLScriptElement.extJavascript.onload
(JOB0000_expand_1000x50to500.html:91)

In addition, I noticed that under the publishing settings you entered a '.'
into the Image and Create js assets path. Is that the same as if you would
toggle the folder off? Because if you toggle off the folder it also exports
into the same directory. Not sure if that is related or not...

Is there another email I can contact you at with screenshots?
Thanks!

**Comment by bastole** [comment]
@dada78 feel free to email me on bastole@gmail.com
There was a conflict in my repos and I've just fixed it - sorry about that. For some reason old updates were committed instead. 
Expand banner should work fine now.

'.' is pretty much same as toggling export settings off I think.

cheers
H

**Comment by ManuWilliams-atx** [comment]
Han, this is awesome! Thanks so much for sharing this! Works great!
